services:
  db:
    container_name: forgejo_db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${BASE_PATH}/postgres:/var/lib/postgresql/data
    networks:
      internal: {}

  forgejoCertbot:
    container_name: forgejoCertbot
    image: certbot/dns-cloudflare
    volumes:
      - ${BASE_PATH}/certbot/conf:/etc/letsencrypt
      - ${BASE_PATH}/certbot/cloudflare.ini:/cloudflare.ini:ro
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      internal: {}

  forgejo:
    container_name: forgejo
    image: codeberg.org/forgejo/forgejo:14
    restart: always
    depends_on:
      - db
    environment:
      USER_UID: 1000
      USER_GID: 1000
      DB_TYPE: postgres
      DB_HOST: forgejo_db:5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWD: ${DB_PASSWORD}
      # --- SSL & DOMAIN SETTINGS ---
      FORGEJO__server__PROTOCOL: https
      FORGEJO__server__HTTP_PORT: 443
      FORGEJO__server__CERT_FILE: /etc/letsencrypt/live/${FORGEJO_DOMAIN}/fullchain.pem
      FORGEJO__server__KEY_FILE: /etc/letsencrypt/live/${FORGEJO_DOMAIN}/privkey.pem
      FORGEJO__server__DOMAIN: ${FORGEJO_DOMAIN}
      FORGEJO__server__ROOT_URL: https://${FORGEJO_DOMAIN}
      FORGEJO__server__SSH_DOMAIN: ${FORGEJO_DOMAIN}
      FORGEJO__server__SSH_PORT: 22
      FORGEJO__webhook__ALLOWED_HOST_LIST: ${ALLOWED_HOST}
    volumes:
      - ${BASE_PATH}/data:/data
      - ${BASE_PATH}/certbot/conf:/etc/letsencrypt:ro
    networks:
      vlan23:
        ipv4_address: ${VLAN23_IP}
      internal:
        aliases:
          - ${FORGEJO_DOMAIN}
    ports:
      - "3443:443"
      - "222:22"

  forgejo_runner:
    container_name: forgejo_runner
    image: code.forgejo.org/forgejo/runner:12
    restart: always
    user: root
    command: forgejo-runner daemon -c /config.yaml
    working_dir: /data
    depends_on:
      - forgejo
    environment:
      # These are secondary to the config file but good to keep
      FORGEJO_INSTANCE_URL: "https://${FORGEJO_DOMAIN}"
      FORGEJO_RUNNER_REGISTRATION_TOKEN: ${FORGEJO_RUNNER_TOKEN}
    volumes:
      - ${BASE_PATH}/runner/data:/data
      - ${BASE_PATH}/runner/config.yaml:/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      internal: {}

networks:
  vlan23:
    external: true
  internal:
    driver: bridge