services:
  db:
    container_name: gitea_db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${GITEA_BASE_PATH}/postgres:/var/lib/postgresql/data
    networks:
      internal: {}

  gitea:
    container_name: gitea
    image: gitea/gitea:main-nightly
    restart: always
    depends_on:
      - db
    environment:
      USER_UID: 1000
      USER_GID: 1000
      DB_TYPE: postgres
      DB_HOST: gitea_db:5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWD: ${POSTGRES_PASSWORD}
      GITEA__server__DOMAIN: ${GITEA_DOMAIN}
      GITEA__server__ROOT_URL: ${GITEA_ROOT_URL}
      GITEA__server__HTTP_PORT: 80
      GITEA__server__SSH_DOMAIN: ${GITEA_DOMAIN}
      GITEA__server__SSH_PORT: 22
      GITEA__webhook__ALLOWED_HOST_LIST: ${GITEA_WEBHOOK_ALLOWED_HOSTS}
    volumes:
      - ${GITEA_BASE_PATH}/data:/data
    networks:
      vlan23:
        ipv4_address: ${GITEA_IP}
      internal: {}
    ports:
      - "8080:80"
      - "2222:22"

  runner:
    container_name: gitea_runner
    image: docker.io/gitea/act_runner:nightly
    restart: always
    depends_on:
      - gitea
    environment:
      CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: ${GITEA_INSTANCE_URL}
      GITEA_RUNNER_REGISTRATION_TOKEN: ${GITEA_RUNNER_REGISTRATION_TOKEN}
      GITEA_RUNNER_NAME: ${GITEA_RUNNER_NAME}
      # GITEA_RUNNER_LABELS: ${GITEA_RUNNER_LABELS}   # uncomment if you want to use it
    volumes:
      - ${GITEA_RUNNER_BASE_PATH}/config.yaml:/config.yaml
      - ${GITEA_RUNNER_BASE_PATH}/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      internal: {}

networks:
  vlan23:
    external: true
  internal:
    driver: bridge